export const FETCH_VOTER_DETAILS_REQUESTED = "FETCH_VOTER_DETAILS_REQUESTED";
export const FETCH_VOTER_SUCCESSFULLY = "FETCH_VOTER_SUCCESSFULLY";
export const UPDATE_VOTER_REQUESTED = "UPDATE_VOTER_REQUESTED";
export const UPDATE_VOTER_SUCCESSFULLY = "UPDATE_VOTER_SUCCESSFULLY";
export const DELETE_VOTER_REQUESTED = "DELETE_VOTER_REQUESTED";
export const DELETE_VOTER_SUCCESSFULLY = "DELETE_VOTER_SUCCESSFULLY";
