export const FETCH_VOTER_DETAILS_REQUESTED = "FETCH_VOTER_DETAILS_REQUESTED";
export const FETCH_VOTER_SUCCESSFULLY = "FETCH_VOTER_SUCCESSFULLY";
export const UPLOAD_VOTER_IMAGE_REQUESTED = "UPLOAD_VOTER_IMAGE_REQUESTED";
export const UPLOAD_VOTER_IMAGE_SUCCESSFULLY =
  "UPLOAD_VOTER_IMAGE_SUCCESSFULLY";
export const ADD_VOTER_REQUESTED = "ADD_VOTER_REQUESTED";
export const ADD_VOTER_SUCCESSFULLY = "ADD_VOTER_SUCCESSFULLY";
export const UPDATE_VOTER_REQUESTED = "UPDATE_VOTER_REQUESTED";
export const UPDATE_VOTER_SUCCESSFULLY = "UPDATE_VOTER_SUCCESSFULLY";
export const DELETE_VOTER_REQUESTED = "DELETE_VOTER_REQUESTED";
export const DELETE_VOTER_SUCCESSFULLY = "DELETE_VOTER_SUCCESSFULLY";
export const FETCH_CANDIDATE_DETAILS_REQUESTED =
  "FETCH_CANDIDATE_DETAILS_REQUESTED";
export const FETCH_CANDIDATE_SUCCESSFULLY = "FETCH_CANDIDATE_SUCCESSFULLY";
export const UPLOAD_CANDIDATE_LOGO_REQUESTED =
  "UPLOAD_CANDIDATE_LOGO_REQUESTED";
export const UPLOAD_CANDIDATE_LOGO_SUCCESSFULLY =
  "UPLOAD_CANDIDATE_LOGO_SUCCESSFULLY";
export const ADD_CANDIDATE_REQUESTED = "ADD_CANDIDATE_REQUESTED";
export const ADD_CANDIDATE_SUCCESSFULLY = "ADD_CANDIDATE_SUCCESSFULLY";
export const UPDATE_CANDIDATE_REQUESTED = "UPDATE_CANDIDATE_REQUESTED";
export const UPDATE_CANDIDATE_SUCCESSFULLY = "UPDATE_CANDIDATE_SUCCESSFULLY";
export const DELETE_CANDIDATE_REQUESTED = "DELETE_CANDIDATE_REQUESTED";
export const DELETE_CANDIDATE_SUCCESSFULLY = "DELETE_CANDIDATE_SUCCESSFULLY";
