export const ADMIN_LOGIN_REQUESTED = "ADMIN_LOGIN_REQUESTED";
export const ADMIN_LOGIN_SUCCESSFULLY = "ADMIN_LOGIN_SUCCESSFULLY";
export const ADMIN_LOGIN_FAIL = "ADMIN_LOGIN_FAIL";
export const ADMIN_LOGIN_LOADER = "ADMIN_LOGIN_LOADER";
export const ADMIN_DETAILS_REQUESTED = "ADMIN_DETAILS_REQUESTED";
export const ADMIN_DETAILS_SUCCESS = "ADMIN_DETAILS_SUCCESS";
